/*
 * This source file was generated by the Gradle 'init' task
 */
package linkedlist;

public class App {

    public static void main(String[] args) {
        JunaLinkedList list = new JunaLinkedList();
        
        list.tambahDepan(20);
        // System.out.println("Linked List berhasil dibuat");
        list.cetaklist();

        list.tambahDepan(10);
        list.cetaklist();

        list.tambahBelakang(30);
        list.cetaklist();

        list.tambahBelakang(40);
        list.cetaklist();

        System.out.println("angka 30 ada di dalam: " + list.cari(30));

        list.delete(20);
        list.cetaklist();

        list.delete(10);
        list.cetaklist();

        
        System.out.println("angka 100 ada di dalam: " + list.cari(100));
    }
}
